### ISSUE TITLE
Wrong import statement and pcz module

### ISSUE THREAD

**Issue by Querela** [uhh-lt/sensegram#25]
https://github.com/uhh-lt/sensegram/blob/221c830c1c1adc64ffbdac19b5627722e06aa3c3/train.py#L13

Change to:

```python
import pcz.disamgiguate_sense_clusters
```

Because:

```python
Traceback (most recent call last):
  File "train.py", line 114, in <module>
    main()
  File "train.py", line 106, in main
    pcz.disambiguate_sense_clusters.run(clusters_with_isas_fpath, clusters_disambiguated_fpath)
AttributeError: module 'pcz' has no attribute 'disambiguate_sense_clusters'
```

---

And:
https://github.com/uhh-lt/sensegram/blob/221c830c1c1adc64ffbdac19b5627722e06aa3c3/train.py#L106

Change to:

```python
        pcz.disambiguate_sense_clusters.run(clusters_with_isas_fpath, clusters_disambiguated_fpath)
```

Because:

```python
Traceback (most recent call last):
  File "train.py", line 114, in <module>
    main()
  File "train.py", line 106, in main
    pcz.disamgiguate_sense_clusters.run(clusters_with_isas_fpath, clusters_disambiguated_fpath)
AttributeError: module 'pcz' has no attribute 'disamgiguate_sense_clusters'
```

**Comment by alexanderpanchenko** [comment]
Thank you? Could you send a pull request? This way you will be among the contributors to the project.
